#!/usr/bin/env bash
set -euo pipefail
KORYMB_SCRIPT="/opt/data/scripts/korymb-sql.sh"
FLEUR_SCRIPT="/opt/data/scripts/fleur-sql.sh"
MANDALA_SCRIPT="/opt/data/scripts/mandala-sql.sh"
fail() { echo "STATUS: FAIL — $1" >&2; exit 1; }
[[ -x "$KORYMB_SCRIPT" ]] || fail "korymb-sql.sh introuvable"
[[ -x "$FLEUR_SCRIPT" ]] || fail "fleur-sql.sh introuvable"
[[ -x "$MANDALA_SCRIPT" ]] || fail "mandala-sql.sh introuvable"
[[ -f /opt/data/.env ]] || fail "/opt/data/.env introuvable"
echo "=== Eludein DB Check ==="
echo "Korymb+Fleur DB: juehpsnqkm60d2o6dhs38c5t | Mandala DB: p11nw75ijqbg4lfzmwbw2m3m"
echo ""
korymb_ws="$("$KORYMB_SCRIPT" "SELECT COUNT(*) AS n FROM korymb_workspaces LIMIT 1" | tail -1)" || fail "Korymb workspaces"
korymb_jobs="$("$KORYMB_SCRIPT" "SELECT COUNT(*) AS n FROM jobs LIMIT 1" | tail -1)" || fail "Korymb jobs"
fleur_users="$("$FLEUR_SCRIPT" "SELECT COUNT(*) AS n FROM wp_users LIMIT 1" | tail -1)" || fail "Fleur users"
fleur_tables="$("$FLEUR_SCRIPT" "SELECT COUNT(*) AS n FROM information_schema.tables WHERE table_schema='default' AND table_name LIKE 'wp_fleur_%'" | tail -1)" || fail "Fleur tables"
mandala_com="$("$MANDALA_SCRIPT" "SELECT COUNT(*) AS n FROM mdl_mandala_communities LIMIT 1" | tail -1)" || fail "Mandala communities"
mandala_tables="$("$MANDALA_SCRIPT" "SELECT COUNT(*) AS n FROM information_schema.tables WHERE table_schema='default' AND table_name LIKE 'mdl_%'" | tail -1)" || fail "Mandala tables"
echo "Korymb workspaces : $korymb_ws"
echo "Korymb jobs         : $korymb_jobs"
echo "Fleur users         : $fleur_users"
echo "Fleur tables        : $fleur_tables"
echo "Mandala communities : $mandala_com"
echo "Mandala tables      : $mandala_tables"
echo ""
echo "STATUS: OK — korymb-sql.sh / fleur-sql.sh / mandala-sql.sh uniquement. Jamais root, jamais Python SQL."
